node {
    stage("Git Clone"){
    git 'https://github.com/mgjerazi/AKS_Docker_Terraform_Ansible_AzureDevOpsPipelines.git'
    }


    stage("Docker Build"){
        sh  "cd Backend && docker build -t mariolgjerazi/backendquiz:${env.BUILD_ID} ."
    }
    stage("Push Docker Image"){

     sh "docker login -u mariolgjerazi -p Kursi123!"
}
    sh "docker push mariolgjerazi/backendquiz:${env.BUILD_ID}"
    }
    stage('Deploy image to AKS-Test') {
          withCredentials([usernamePassword(credentialsId: 'AZURE', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            sh "az login -u ${USERNAME} -p ${PASSWORD}"
            sh "az account set -s ${AZURE_SUBSCRIPTION_ID}"
            sh "az aks install-cli"
            sh "az aks get-credentials --resource-group merkato_rg --name k8s-quiz-test"
            sh "kubectl set image deployment/backend backend=backendquiz=${imagename}:${BUILD_ID}"
      }
    }
}